Copy fix command to clipboard

diff --git a/src/listen b/src/listen
--- a/src/listen
+++ b/src/listen
@@ -1,12 +1,11 @@
 #!/bin/bash
 
 RED="\e[31m"
-BLUE="\e[34m"
-YELLOW="\e[33m"
-ENDCOLOR="\e[0m"
+YELLOW=$'\e[33m'
+RESET="\e[0m"
 
 if [[ "$#" -ne 2 ]]; then
-    echo -e "${RED}[x]${ENDCOLOR} Error: Incorrect number of arguments"
+    echo -e "${RED}[x]${RESET} Error: Incorrect number of arguments"
 
     echo -e "\nUsage:"
     echo -e "\tlisten linux <port>"
@@ -15,10 +14,16 @@ if [[ "$#" -ne 2 ]]; then
 fi
 
 if ! command -v rcat >/dev/null 2>&1; then
-    echo -e "${RED}[x] rcat not installed"
+    echo -e "${RED}[x]${RESET} rcat not installed"
     exit 1
 fi
 
+if [[ "$XDG_SESSION_TYPE" == "x11" ]] && ! command -v xclip >/dev/null 2>&1; then
+    echo -e "${RED}[x]${RESET} xclip not installed"
+    exit 1
+fi
+
+copy=""
 if uname -r | grep -q "microsoft"; then
     copy='/mnt/c/Windows/System32/clip.exe'
 elif [[ "$XDG_SESSION_TYPE" == "x11" ]]; then
@@ -29,17 +34,18 @@ fi
 
 if [[ "$1" == "linux" ]]; then
     read -r rows cols < <(stty size)
-    echo -n "stty rows $rows cols $cols" | $copy
-    echo -e "\n${BLUE}[!]${ENDCOLOR} Fix stty size on the reverse shell"
-    echo -e "${BLUE}[!]${ENDCOLOR} ${YELLOW}stty rows $rows cols $cols${ENDCOLOR} copied to clipboard\n"
+    fix_command="export TERM=xterm-256color; stty rows $rows cols $cols; alias ls='ls --color=auto'; alias grep='grep --color=auto'; alias ip='ip --color=auto'"
+    echo -n "$fix_command" | $copy
+    echo -e "\n${YELLOW}[!]${RESET} Fix command copied to clipboard"
+    echo -e "\n${YELLOW}[!]${RESET} Fix command: $fix_command"
 
     stty raw -echo
-    rcat listen -ie "$(command -v script) -qc $(command -v bash) /dev/null; export TERM=xterm-256color; alias ls='ls --color=auto'; alias grep='grep --color=auto'; alias ip='ip --color=auto'" "$2"
+    rcat listen -ie "/usr/bin/env python3 -c 'import pty; pty.spawn(\"/bin/bash\")'" "$2"
     reset
 elif [[ "$1" == "windows" ]]; then
     echo -ne "\n"
     rlwrap ncat -lvnp "$2"
 else
-    echo -e "\n${RED}[x]${ENDCOLOR} Invalid option\n"
+    echo -e "\n${RED}[x]${RESET} Invalid option\n"
     exit 1
 fi
