Consistency on docs

diff --git a/src/scan b/src/scan
--- a/src/scan
+++ b/src/scan
@@ -6,6 +6,7 @@ ENDCOLOR="\e[0m"
 outfile_tcp="tcp_scan.txt"
 outfile_udp="udp_scan.txt"
 udp=0
+help=0
 current_filename=""
 positional_amount=0
 target=""
@@ -16,6 +17,13 @@ function ctrl_c() {
     sudo rm -f "$current_filename"
     echo -e "\n${RED}[x]${ENDCOLOR} Aborting scan" >&2
     exit 1
+}
+
+function usage() {
+    echo "Usage: scan [options] <ip>"
+    echo -e "\nOptions:"
+    echo -e "\t-u\tUDP scan"
+    echo -e "\t-o FILE\toutput file name"
 }
 
 while [ "$#" -gt 0 ]; do
@@ -29,20 +37,21 @@ while [ "$#" -gt 0 ]; do
         current_filename="$2"
         shift 2
         ;;
-
-    --outfile=*)
-        current_filename="${1#*=}"
+    -h)
+        help=1
         shift 1
         ;;
 
     -*)
-        echo -e "${RED}[x]${ENDCOLOR} Invalid option: $1" >&2
+        echo -e "${RED}[x]${ENDCOLOR} Error: Invalid option: $1\n" >&2
+        usage
         exit 1
         ;;
     *)
         positional_amount=$((positional_amount + 1))
         if [[ "$positional_amount" -gt 1 ]]; then
-            echo -e "${RED}[X]${ENDCOLOR} Can't have more than 1 positional argument" >&2
+            echo -e "${RED}[X]${ENDCOLOR} Error: Can't have more than 1 positional argument\n" >&2
+            usage
             exit 1
         fi
         target="$1"
@@ -50,6 +59,11 @@ while [ "$#" -gt 0 ]; do
         ;;
     esac
 done
+
+if [[ "$help" -eq 1 ]]; then
+    usage
+    exit 0
+fi
 
 if [[ -z "$current_filename" ]]; then
     if [[ "$udp" -eq 1 ]]; then
@@ -60,7 +74,8 @@ if [[ -z "$current_filename" ]]; then
 fi
 
 if [[ -z "$target" ]]; then
-    echo -e "${RED}[x]${ENDCOLOR} Please provide IP address or domain name to scan" >&2
+    echo -e "${RED}[x]${ENDCOLOR} Error: Missing IP or hostname\n" >&2
+    usage
     exit 1
 fi
 
